_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
                - 98
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
                - 98
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.21
            "5": 0.19.9
            "6": 4.50.3
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 1
deepspeed_config:
    value: ds_config.json
early_stopping_patience:
    value: 3
epochs:
    value: 10
learning_rate:
    value: 5e-05
local_rank:
    value: 0
log_steps:
    value: 10
lora_alpha:
    value: 32
lora_dropout:
    value: 0.1
lora_r:
    value: 8
lora_target_modules:
    value: q_proj,v_proj
margin:
    value: 1
max_length:
    value: 512
model_name:
    value: mistralai/Mistral-7B-v0.1
output_dir:
    value: reward_model_out
train_dirs:
    value: ../VisualWebArena/reddit_gpt4v_som,../VisualWebArena/shopping_gpt4v_som
val_dirs:
    value: ../VisualWebArena/classifieds_gpt4v_som
wandb_project:
    value: reward_model_project
